### ISSUE TITLE
Polymer 1.0

### ISSUE THREAD

**Issue by yogaraptor** [YannickDot/x-iscroll#1]
I was going to submit a PR upgrading this element to work with Polymer 1.0 (which is not backwards-compatible with previous versions), but due to the Polymer syntax changes it was basically a complete rewrite. I've therefore published my own element [rv-iscroll](https://github.com/itsravenous/rv-iscroll). I've given attribution to your work there; I hope you don't mind :)

**Comment by YannickDot** [comment]
Hey, sorry for taking so much time to answer 😕
Of course you did right, I'd no more time to stay in touch with Polymer framework changes.

Thank you for your work mate!
I'll add a link to your rv-iscroll at the top of the README. 😉

**Comment by yogaraptor** [comment]
No worries dude - we none of us have time! Thanks for the link.
